# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-14 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltReview_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(default='1990-01-01'),
            preserve_default=False,
        ),
    ]
